apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: mypod
spec:
  containers:
  - image: nginx
    name: mypod
    resources:
      requests:
        cpu: 500m
        memory: 256Mi
      limits:
        cpu: 700m
        memory: 512Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
