apiVersion: v1
kind: LimitRange
metadata:
  name: mylimitrange
spec:
  limits:
    - default:
        cpu: 500m
      defaultRequest:
        cpu: 500m
      max: 
        cpu: 1000m
      type: Container
