apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mypodsc
  name: mypodsc
spec:
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: myclaim
  containers:
  - image: belsaadi/voll1
    name: mypodsc
    volumeMounts:
      - name: mypv
        mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
