apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    apps: mydeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      apps: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata: 
      name: mypod
      labels:
        apps: frontend
    spec:
      containers:
        - name: mypod
          image: belsaadi/nginx-vim-server2:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3 
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 3
            failureThreshold: 3 
          startupProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3 
  
