apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
    - name: mypodcontainer
      image: busybox
      env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: myconfigmap1
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: myconfigmap1
              key: APP_ENV
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: myconfigmap1
              key: APP_PORT
      command:
        - sh
        - -c
        - |
          echo "Application: = $APP_NAME"
          echo "Environment: = $APP_ENV"  
          echo "Port: = $APP_PORT"
          sleep 3600    
