apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
spec:
  hostPath:
    path: /mnt/data 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
