apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  volumeType: 
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: main
  hostPath:
    path: /mnt/data
