apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  volumeType: 
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: main
  hostPath:
    path: /mnt/data1
