apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefullset
spec:
  selector:
    matchLabels:
      app: mypod 
  serviceName: mysvc
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mypod
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
