apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mycontainer
      image: busybox
      command: [ 'sh','-c','sleep infinity']
      volumeMounts:
        - name: myvolume
          mountPath: /etc/myapp/PORT.config
  volumes:
    - name: myvolume
      configMap:
        name: myconfigmap
        
