apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod2
  name: pod2
spec:
  containers:
  - image: busybox
    name: pod2
    command: ['sh','-c','sleep infinity']
    envFrom:
      - configMapRef:
          name: myconfigmap
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
