apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mydockerconfigjsonpod
  name: mydockerconfigjsonpod
spec:
  containers:
  - image: belsaadi/nginx-vim-server2
    name: mydockerconfigjsonpod
  imagePullSecrets:
    - name: mysecretdockerconfigjson
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
