apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myopaquepod3
  name: myopaquepod3
spec:
  containers:
  - image: nginx
    name: myopaquepod3
    volumeMounts:
      - name: myvolumesecret
        mountPath: /etc/opaque
  volumes:
    - name: myvolumesecret
      secret:
        secretName: opaque
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
