apiVersion: v1
kind: Pod
metadata:
  labels:


























  
    run: pods
  name: pods
spec:
  containers:
    - image: nginx
      name: pods
      env:
       - name: username
         valueFrom:
           secretKeyRef:
             name: opaque
             key: username
       - name: port
         valueFrom:
           secretKeyRef:
             name: opaque
             key: port
       - name: version
         valueFrom:
           secretKeyRef:
             name: opaque
             key: version 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
