apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myopaquepod2
  name: myopaquepod2
spec:
  containers:
  - image: nginx
    name: myopaquepod2
    envFrom:
      - secretRef:
          name: opaque
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
