apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJiZWxzYWFkaSIsInBhc3N3b3JkIjoiU3RhdHRpYXJldDIwMTY2NiIsImF1dGgiOiJZbVZzYzJGaFpHazZVM1JoZEhScFlYSmxkREl3TVRZMk5nPT0ifX19
kind: Secret
metadata:
  name: mysecretdockerconfigjson
type: kubernetes.io/dockerconfigjson
